import { norm } from "./hash.js";

/* Built-in Dutch category defaults. These apply automatically in categorize()
 * AFTER a user's own rules (and a manual tx.category), so they give sensible
 * categories out of the box for the average Dutch household while any
 * user-defined rule or manual override still wins.
 *
 * Matching is the same as user rules: the (normalized) `match` string is tested
 * as a substring of norm(counterparty + " " + description). Two consequences
 * shaped this list:
 *   1. ORDER MATTERS — the first match wins, so a specific product is listed
 *      before a broader merchant ("amazon prime" -> Entertainment appears above
 *      "amazon" -> Online shopping; "uber eats"/"bolt food" -> Eten sit above
 *      "uber"/"bolt" -> Transport).
 *   2. NO SHORT/AMBIGUOUS TOKENS — a match is a plain substring, so entries that
 *      would collide with common words are avoided (e.g. bare "spar" is a
 *      substring of "sparen" and would mislabel savings transfers; "ret",
 *      "cak", bare "bp"/"total"/"cz" are omitted for the same reason). Accented
 *      variants are listed explicitly ("cafe"/"café") because norm lowercases
 *      but does not strip accents. */

export type CategoryRule = { match: string; category: string };

export const NL_CATEGORY_RULES: readonly CategoryRule[] = [
  // --- overlap priority: specific product before its broader merchant ---
  { match: "amazon prime", category: "Entertainment" },
  { match: "prime video", category: "Entertainment" },
  { match: "amazon music", category: "Entertainment" },
  { match: "google play", category: "Entertainment" },
  { match: "youtube premium", category: "Entertainment" },
  { match: "apple.com/bill", category: "Abonnementen" },
  { match: "microsoft 365", category: "Abonnementen" },
  { match: "office 365", category: "Abonnementen" },

  // --- Boodschappen ---
  { match: "albert heijn", category: "Boodschappen" },
  { match: "ah to go", category: "Boodschappen" },
  { match: "ah xl", category: "Boodschappen" },
  { match: "appie", category: "Boodschappen" },
  { match: "jumbo", category: "Boodschappen" },
  { match: "lidl", category: "Boodschappen" },
  { match: "aldi", category: "Boodschappen" },
  { match: "plus supermarkt", category: "Boodschappen" },
  { match: "dirk van den broek", category: "Boodschappen" },
  { match: "dirk vd broek", category: "Boodschappen" },
  { match: "coop supermarkt", category: "Boodschappen" },
  { match: "dekamarkt", category: "Boodschappen" },
  { match: "vomar", category: "Boodschappen" },
  { match: "hoogvliet", category: "Boodschappen" },
  { match: "poiesz", category: "Boodschappen" },
  { match: "boni", category: "Boodschappen" },
  { match: "jan linders", category: "Boodschappen" },
  { match: "nettorama", category: "Boodschappen" },
  { match: "ekoplaza", category: "Boodschappen" },
  { match: "marqt", category: "Boodschappen" },
  { match: "picnic", category: "Boodschappen" },
  { match: "crisp", category: "Boodschappen" },
  { match: "gorillas", category: "Boodschappen" },
  { match: "getir", category: "Boodschappen" },
  { match: "bakkerij", category: "Boodschappen" },
  { match: "bakker bart", category: "Boodschappen" },
  { match: "slagerij", category: "Boodschappen" },
  { match: "slager", category: "Boodschappen" },
  { match: "kaashandel", category: "Boodschappen" },
  { match: "groenteboer", category: "Boodschappen" },
  { match: "toko", category: "Boodschappen" },
  { match: "avondwinkel", category: "Boodschappen" },
  { match: "supermarkt", category: "Boodschappen" },

  // --- Eten & drinken (must precede Transport for uber eats / bolt food) ---
  { match: "thuisbezorgd", category: "Eten & drinken" },
  { match: "takeaway", category: "Eten & drinken" },
  { match: "uber eats", category: "Eten & drinken" },
  { match: "ubereats", category: "Eten & drinken" },
  { match: "bolt food", category: "Eten & drinken" },
  { match: "deliveroo", category: "Eten & drinken" },
  { match: "dominos", category: "Eten & drinken" },
  { match: "domino's", category: "Eten & drinken" },
  { match: "new york pizza", category: "Eten & drinken" },
  { match: "mcdonald", category: "Eten & drinken" },
  { match: "burger king", category: "Eten & drinken" },
  { match: "kfc", category: "Eten & drinken" },
  { match: "subway", category: "Eten & drinken" },
  { match: "febo", category: "Eten & drinken" },
  { match: "kwalitaria", category: "Eten & drinken" },
  { match: "starbucks", category: "Eten & drinken" },
  { match: "coffee company", category: "Eten & drinken" },
  { match: "la place", category: "Eten & drinken" },
  { match: "bagels beans", category: "Eten & drinken" },
  { match: "restaurant", category: "Eten & drinken" },
  { match: "eetcafe", category: "Eten & drinken" },
  { match: "eetcafé", category: "Eten & drinken" },
  { match: "grand cafe", category: "Eten & drinken" },
  { match: "grand café", category: "Eten & drinken" },
  { match: "cafe", category: "Eten & drinken" },
  { match: "café", category: "Eten & drinken" },
  { match: "brasserie", category: "Eten & drinken" },
  { match: "bistro", category: "Eten & drinken" },
  { match: "snackbar", category: "Eten & drinken" },
  { match: "cafetaria", category: "Eten & drinken" },
  { match: "pizzeria", category: "Eten & drinken" },
  { match: "sushi", category: "Eten & drinken" },

  // --- Transport ---
  { match: "uber", category: "Transport" },
  { match: "bolt", category: "Transport" },
  { match: "ns groep", category: "Transport" },
  { match: "ns reizigers", category: "Transport" },
  { match: "ns.nl", category: "Transport" },
  { match: "ns dagkaart", category: "Transport" },
  { match: "ov-chipkaart", category: "Transport" },
  { match: "ovpay", category: "Transport" },
  { match: "ov pay", category: "Transport" },
  { match: "gvb", category: "Transport" },
  { match: "connexxion", category: "Transport" },
  { match: "arriva", category: "Transport" },
  { match: "qbuzz", category: "Transport" },
  { match: "flixbus", category: "Transport" },
  { match: "blablacar", category: "Transport" },
  { match: "greenwheels", category: "Transport" },
  { match: "mywheels", category: "Transport" },
  { match: "felyx", category: "Transport" },
  { match: "go sharing", category: "Transport" },
  { match: "donkey republic", category: "Transport" },
  { match: "swapfiets", category: "Transport" },
  { match: "shell", category: "Transport" },
  { match: "esso", category: "Transport" },
  { match: "texaco", category: "Transport" },
  { match: "tango", category: "Transport" },
  { match: "tinq", category: "Transport" },
  { match: "tamoil", category: "Transport" },
  { match: "total energies", category: "Transport" },
  { match: "q8", category: "Transport" },
  { match: "tankstation", category: "Transport" },
  { match: "benzine", category: "Transport" },
  { match: "parkeren", category: "Transport" },
  { match: "parking", category: "Transport" },
  { match: "q-park", category: "Transport" },
  { match: "qpark", category: "Transport" },
  { match: "yellowbrick", category: "Transport" },
  { match: "parkmobile", category: "Transport" },
  { match: "parkline", category: "Transport" },
  { match: "flitsmeister", category: "Transport" },

  // --- Reizen ---
  { match: "booking.com", category: "Reizen" },
  { match: "airbnb", category: "Reizen" },
  { match: "transavia", category: "Reizen" },
  { match: "klm", category: "Reizen" },
  { match: "ryanair", category: "Reizen" },
  { match: "easyjet", category: "Reizen" },
  { match: "tui.nl", category: "Reizen" },
  { match: "tui reizen", category: "Reizen" },
  { match: "sunweb", category: "Reizen" },
  { match: "expedia", category: "Reizen" },
  { match: "eurostar", category: "Reizen" },
  { match: "thalys", category: "Reizen" },
  { match: "flixtrain", category: "Reizen" },
  { match: "schiphol", category: "Reizen" },
  { match: "hotel", category: "Reizen" },
  { match: "hostel", category: "Reizen" },

  // --- Entertainment ---
  { match: "netflix", category: "Entertainment" },
  { match: "videoland", category: "Entertainment" },
  { match: "disney", category: "Entertainment" },
  { match: "hbo max", category: "Entertainment" },
  { match: "hbomax", category: "Entertainment" },
  { match: "spotify", category: "Entertainment" },
  { match: "apple music", category: "Entertainment" },
  { match: "deezer", category: "Entertainment" },
  { match: "tidal", category: "Entertainment" },
  { match: "youtube", category: "Entertainment" },
  { match: "twitch", category: "Entertainment" },
  { match: "playstation", category: "Entertainment" },
  { match: "nintendo", category: "Entertainment" },
  { match: "xbox", category: "Entertainment" },
  { match: "steamgames", category: "Entertainment" },
  { match: "epic games", category: "Entertainment" },
  { match: "pathe", category: "Entertainment" },
  { match: "pathé", category: "Entertainment" },
  { match: "kinepolis", category: "Entertainment" },
  { match: "vue cinema", category: "Entertainment" },
  { match: "bioscoop", category: "Entertainment" },
  { match: "ticketmaster", category: "Entertainment" },
  { match: "eventim", category: "Entertainment" },
  { match: "paylogic", category: "Entertainment" },
  { match: "cineville", category: "Entertainment" },

  // --- Abonnementen (telecom, software/cloud, nieuws) ---
  { match: "vodafone", category: "Abonnementen" },
  { match: "ziggo", category: "Abonnementen" },
  { match: "kpn", category: "Abonnementen" },
  { match: "t-mobile", category: "Abonnementen" },
  { match: "odido", category: "Abonnementen" },
  { match: "tele2", category: "Abonnementen" },
  { match: "simyo", category: "Abonnementen" },
  { match: "lebara", category: "Abonnementen" },
  { match: "lycamobile", category: "Abonnementen" },
  { match: "hollandsnieuwe", category: "Abonnementen" },
  { match: "youfone", category: "Abonnementen" },
  { match: "ben.nl", category: "Abonnementen" },
  { match: "adobe", category: "Abonnementen" },
  { match: "dropbox", category: "Abonnementen" },
  { match: "icloud", category: "Abonnementen" },
  { match: "google one", category: "Abonnementen" },
  { match: "google storage", category: "Abonnementen" },
  { match: "linkedin", category: "Abonnementen" },
  { match: "chatgpt", category: "Abonnementen" },
  { match: "openai", category: "Abonnementen" },
  { match: "notion", category: "Abonnementen" },
  { match: "canva", category: "Abonnementen" },
  { match: "patreon", category: "Abonnementen" },
  { match: "de volkskrant", category: "Abonnementen" },
  { match: "de telegraaf", category: "Abonnementen" },
  { match: "algemeen dagblad", category: "Abonnementen" },
  { match: "dagblad trouw", category: "Abonnementen" },
  { match: "het parool", category: "Abonnementen" },
  { match: "nrc", category: "Abonnementen" },

  // --- Wonen & energie ---
  { match: "vattenfall", category: "Wonen & energie" },
  { match: "eneco", category: "Wonen & energie" },
  { match: "essent", category: "Wonen & energie" },
  { match: "greenchoice", category: "Wonen & energie" },
  { match: "vandebron", category: "Wonen & energie" },
  { match: "budget energie", category: "Wonen & energie" },
  { match: "oxxio", category: "Wonen & energie" },
  { match: "engie", category: "Wonen & energie" },
  { match: "pure energie", category: "Wonen & energie" },
  { match: "energiedirect", category: "Wonen & energie" },
  { match: "vitens", category: "Wonen & energie" },
  { match: "waternet", category: "Wonen & energie" },
  { match: "pwn", category: "Wonen & energie" },
  { match: "brabant water", category: "Wonen & energie" },
  { match: "dunea", category: "Wonen & energie" },
  { match: "evides", category: "Wonen & energie" },
  { match: "huur", category: "Wonen & energie" },
  { match: "hypotheek", category: "Wonen & energie" },
  { match: "woningcorporatie", category: "Wonen & energie" },
  { match: "vesteda", category: "Wonen & energie" },

  // --- Verzekeringen ---
  { match: "verzekering", category: "Verzekeringen" },
  { match: "zilveren kruis", category: "Verzekeringen" },
  { match: "cz zorg", category: "Verzekeringen" },
  { match: "vgz", category: "Verzekeringen" },
  { match: "menzis", category: "Verzekeringen" },
  { match: "ohra", category: "Verzekeringen" },
  { match: "unive", category: "Verzekeringen" },
  { match: "univé", category: "Verzekeringen" },
  { match: "fbto", category: "Verzekeringen" },
  { match: "ditzo", category: "Verzekeringen" },
  { match: "centraal beheer", category: "Verzekeringen" },
  { match: "nationale nederlanden", category: "Verzekeringen" },
  { match: "aegon", category: "Verzekeringen" },
  { match: "asr", category: "Verzekeringen" },
  { match: "allianz", category: "Verzekeringen" },
  { match: "interpolis", category: "Verzekeringen" },
  { match: "inshared", category: "Verzekeringen" },
  { match: "reaal", category: "Verzekeringen" },

  // --- Gezondheid (apotheek, drogist, medisch, sport) ---
  { match: "apotheek", category: "Gezondheid" },
  { match: "kruidvat", category: "Gezondheid" },
  { match: "etos", category: "Gezondheid" },
  { match: "trekpleister", category: "Gezondheid" },
  { match: "da drogist", category: "Gezondheid" },
  { match: "holland en barrett", category: "Gezondheid" },
  { match: "holland & barrett", category: "Gezondheid" },
  { match: "huisarts", category: "Gezondheid" },
  { match: "tandarts", category: "Gezondheid" },
  { match: "fysio", category: "Gezondheid" },
  { match: "ziekenhuis", category: "Gezondheid" },
  { match: "optiek", category: "Gezondheid" },
  { match: "hans anders", category: "Gezondheid" },
  { match: "pearle", category: "Gezondheid" },
  { match: "specsavers", category: "Gezondheid" },
  { match: "basic-fit", category: "Gezondheid" },
  { match: "basic fit", category: "Gezondheid" },
  { match: "fit for free", category: "Gezondheid" },
  { match: "sportcity", category: "Gezondheid" },
  { match: "anytime fitness", category: "Gezondheid" },
  { match: "sportschool", category: "Gezondheid" },
  { match: "fitness", category: "Gezondheid" },

  // --- Kleding & winkelen ---
  { match: "zalando", category: "Kleding & winkelen" },
  { match: "h&m", category: "Kleding & winkelen" },
  { match: "zara", category: "Kleding & winkelen" },
  { match: "primark", category: "Kleding & winkelen" },
  { match: "c&a", category: "Kleding & winkelen" },
  { match: "we fashion", category: "Kleding & winkelen" },
  { match: "wehkamp", category: "Kleding & winkelen" },
  { match: "de bijenkorf", category: "Kleding & winkelen" },
  { match: "bijenkorf", category: "Kleding & winkelen" },
  { match: "hema", category: "Kleding & winkelen" },
  { match: "action", category: "Kleding & winkelen" },
  { match: "bristol", category: "Kleding & winkelen" },
  { match: "van haren", category: "Kleding & winkelen" },
  { match: "vanharen", category: "Kleding & winkelen" },
  { match: "scapino", category: "Kleding & winkelen" },
  { match: "decathlon", category: "Kleding & winkelen" },
  { match: "intersport", category: "Kleding & winkelen" },
  { match: "perry sport", category: "Kleding & winkelen" },
  { match: "uniqlo", category: "Kleding & winkelen" },
  { match: "nike", category: "Kleding & winkelen" },
  { match: "adidas", category: "Kleding & winkelen" },
  { match: "douglas", category: "Kleding & winkelen" },
  { match: "rituals", category: "Kleding & winkelen" },
  { match: "ici paris", category: "Kleding & winkelen" },

  // --- Huis & tuin ---
  { match: "ikea", category: "Huis & tuin" },
  { match: "praxis", category: "Huis & tuin" },
  { match: "gamma", category: "Huis & tuin" },
  { match: "karwei", category: "Huis & tuin" },
  { match: "hornbach", category: "Huis & tuin" },
  { match: "intratuin", category: "Huis & tuin" },
  { match: "tuincentrum", category: "Huis & tuin" },
  { match: "leen bakker", category: "Huis & tuin" },
  { match: "kwantum", category: "Huis & tuin" },
  { match: "jysk", category: "Huis & tuin" },
  { match: "xenos", category: "Huis & tuin" },
  { match: "blokker", category: "Huis & tuin" },
  { match: "hubo", category: "Huis & tuin" },
  { match: "welkoop", category: "Huis & tuin" },

  // --- Elektronica ---
  { match: "coolblue", category: "Elektronica" },
  { match: "mediamarkt", category: "Elektronica" },
  { match: "media markt", category: "Elektronica" },
  { match: "bcc", category: "Elektronica" },
  { match: "apple store", category: "Elektronica" },

  // --- Online shopping (after amazon prime/music above) ---
  { match: "bol.com", category: "Online shopping" },
  { match: "amazon", category: "Online shopping" },
  { match: "aliexpress", category: "Online shopping" },
  { match: "marktplaats", category: "Online shopping" },
  { match: "vinted", category: "Online shopping" },
  { match: "temu", category: "Online shopping" },
  { match: "shein", category: "Online shopping" },
  { match: "etsy", category: "Online shopping" },
  { match: "ebay", category: "Online shopping" },

  // --- Belastingen & overheid ---
  { match: "belastingdienst", category: "Belastingen & overheid" },
  { match: "cjib", category: "Belastingen & overheid" },
  { match: "duo", category: "Belastingen & overheid" },
  { match: "gemeente", category: "Belastingen & overheid" },
  { match: "waterschap", category: "Belastingen & overheid" },
  { match: "cbr", category: "Belastingen & overheid" },
  { match: "rdw", category: "Belastingen & overheid" },
  { match: "svb", category: "Belastingen & overheid" },
  { match: "uwv", category: "Belastingen & overheid" },
  { match: "kvk", category: "Belastingen & overheid" },

  // --- Sparen & beleggen ("spaarrekening" is a safe full word — bare "spar"
  //     is deliberately NOT used as it is a substring of "sparen") ---
  { match: "spaarrekening", category: "Sparen & beleggen" },
  { match: "degiro", category: "Sparen & beleggen" },
  { match: "de giro", category: "Sparen & beleggen" },
  { match: "brand new day", category: "Sparen & beleggen" },
  { match: "meesman", category: "Sparen & beleggen" },
  { match: "etoro", category: "Sparen & beleggen" },
  { match: "trade republic", category: "Sparen & beleggen" },
  { match: "scalable capital", category: "Sparen & beleggen" },
  { match: "trading 212", category: "Sparen & beleggen" },
  { match: "binance", category: "Sparen & beleggen" },
  { match: "coinbase", category: "Sparen & beleggen" },
  { match: "bitvavo", category: "Sparen & beleggen" },

  // --- Goede doelen ---
  { match: "rode kruis", category: "Goede doelen" },
  { match: "unicef", category: "Goede doelen" },
  { match: "greenpeace", category: "Goede doelen" },
  { match: "artsen zonder grenzen", category: "Goede doelen" },
  { match: "hartstichting", category: "Goede doelen" },
  { match: "cliniclowns", category: "Goede doelen" },
  { match: "oxfam", category: "Goede doelen" },
  { match: "goede doel", category: "Goede doelen" },
  { match: "donatie", category: "Goede doelen" },
  { match: "giro555", category: "Goede doelen" },

  // --- Huisdieren ---
  { match: "pets place", category: "Huisdieren" },
  { match: "petsplace", category: "Huisdieren" },
  { match: "dierenarts", category: "Huisdieren" },
  { match: "dierenkliniek", category: "Huisdieren" },
  { match: "zooplus", category: "Huisdieren" },
  { match: "dierenspeciaalzaak", category: "Huisdieren" },

  // --- Geldopname ---
  { match: "geldautomaat", category: "Geldopname" },
  { match: "geldopname", category: "Geldopname" },
  { match: "cash opname", category: "Geldopname" },
  { match: "atm", category: "Geldopname" },

  // --- Bankkosten (bank fees) ---
  { match: "kosten zakelijk betalingsverkeer", category: "Bankkosten" },
  { match: "betalingsverkeer", category: "Bankkosten" },
  { match: "betaalpakket", category: "Bankkosten" },
  { match: "bankkosten", category: "Bankkosten" },
  { match: "administratiekosten", category: "Bankkosten" },

  // --- Overboekingen (top-ups / peer transfers / card settlements — not
  //     merchant spend) ---
  { match: "geld toegevoegd", category: "Overboekingen" },
  { match: "geld toevoegen", category: "Overboekingen" },
  { match: "tikkie", category: "Overboekingen" },
  { match: "naar creditcard", category: "Overboekingen" },
];

/* Pre-normalized once at module load so categorize() does a plain substring test
 * per entry (no per-transaction norm of the match strings). */
export const NL_CATEGORY_RULES_NORMALIZED: ReadonlyArray<{ m: string; category: string }> =
  NL_CATEGORY_RULES.map((r) => ({ m: norm(r.match), category: r.category }));
